### ISSUE TITLE
Very much needed add on for Blender - but how to set up preferences and find to use?

### ISSUE THREAD

**Issue by dltanner99** [Digiography/blender_addon_iclone#1]
Excellent and much needed add on for Blender, but after I installed the add on I don't see how to access it either in User Preferences or select it for use with the iClone template. Can you please explain how it is found and works after installation? Thank you!

**Comment by DigiKrafting** [comment]
Apologies for the delayed response, It should come up if you search for "iClone" in addons, in blender 2.79 and prior, be sure to remove any "." full stops (eg blender_addon_iclone_1.0.0, i use "_"'s now in releases to resolve this) in the folder name, as this will cause blender not to see the folder. Reopen this issue if you have any further issues.
