### ISSUE TITLE
Issue with blender 2.8

### ISSUE THREAD

**Issue by shubhajitbasak** [Digiography/blender_addon_iclone#3]
Hi,

I followed the step and installed the addon to blender 2.8

Downloaded the CC Template from CC3 Templates [https://www.reallusion.com/character-creator/custom-outfit.html]

Point the folder in the preference

![image](https://user-images.githubusercontent.com/20750886/67512756-6b283a00-f691-11e9-8c62-5f0a7be3526e.png)

When I am importing I am getting the following options :

![image](https://user-images.githubusercontent.com/20750886/67512875-a62a6d80-f691-11e9-95ad-d011212e2be3.png)

Its expecting a folder with maya as it is written in the script my folder structure is as follows : 

![image](https://user-images.githubusercontent.com/20750886/67513553-f3f3a580-f692-11e9-9721-a7241a10882b.png)

![image](https://user-images.githubusercontent.com/20750886/67513650-2bfae880-f693-11e9-8239-62bc7c819564.png)

But still while I am importing the character its not giving the expected result:

![image](https://user-images.githubusercontent.com/20750886/67513682-4208a900-f693-11e9-9bb2-5cf9997678f0.png)

**Comment by DigiKrafting** [comment]
Hi, the templates are only needed for the base body meshes like in the screenshot [https://github.com/DigiKrafting/blender_addon_reallusion/blob/master/screenshots/ic.png](https://github.com/DigiKrafting/blender_addon_reallusion/blob/master/screenshots/ic.png.) Are you using "Import CC (.fbx)" which is for importing Character Creator fbx's?

**Comment by shubhajitbasak** [comment]
Hi,

I have tried to import in both "Import CC (.fbx)" and "CC Male Template (.fbx)".

in the camera view its look like - 
![image](https://user-images.githubusercontent.com/20750886/67560814-8d629c00-f713-11e9-8868-2794f60fed8d.png)


Though when I render in cycle engine its much better , but it didn't work for eevee though, following a screenshot from cycle render - 

![image](https://user-images.githubusercontent.com/20750886/67561012-f3e7ba00-f713-11e9-99c3-5e5142536796.png)


But still the hair is not rendering correctly.

**Comment by DigiKrafting** [comment]
The hair shader is the hardest to get right, when I get some free time, I'll start working on improving it, Blenders "Principled Hair BSDF" might be the answer, in the meantime you could experiment with the material settings, in particular the Blend Mode.

**Comment by DigiKrafting** [comment]
I just did a test import and noticed that most of the textures were not being assigned to the material as the addon was searching for ".png" files instead of ".jpg", I've just uploaded a fix for this.

https://github.com/DigiKrafting/blender_addon_reallusion/releases/tag/1_4_0
