### ISSUE TITLE
Issue Blender 2.82 - MULTIPLY blend_method

### ISSUE THREAD

**Issue by rootbsd** [Digiography/blender_addon_iclone#4]
Hi

I think blender did an update in the Material class. If you look at the documentation here: https://docs.blender.org/api/current/bpy.types.Material.html there is not "MULTIPLY" in the blend_method.

That's why I have this error message:
![image](https://user-images.githubusercontent.com/4417222/75421431-8904f480-593a-11ea-8d4c-d2b8ec4167f7.png)

I'm not good enough in material to propose a patch... I did some Google search and I'm not sure how to fix it.

P.

**Comment by DigiKrafting** [comment]
Hi, thanks for reporting the error, I've updated the obsolete property: [https://github.com/DigiKrafting/blender_addon_reallusion/releases/latest](https://github.com/DigiKrafting/blender_addon_reallusion/releases/latest)

**Comment by rootbsd** [comment]
it works like a charm.
Thank you!
